Library/Library/ViewComponents/NavBarViewComponent.cs
using Data.DTOs.Notification;
using Microsoft.AspNetCore.Mvc;
using Service.FrenidShipServices;
using Service.User;
using System.Runtime.Intrinsics.X86;

namespace Library.ViewComponents
{
    public class NavBarViewComponent : ViewComponent
    {
        private readonly IAppUserService _appUserService;
        private readonly IFreindShipService _freindShipService;
        public NavBarViewComponent(IAppUserService appUserService, IFreindShipService freindShipService)
        {
            _appUserService = appUserService;
            _freindShipService = freindShipService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var IsSignIn = _appUserService.IsSignIn();
            if (IsSignIn)
            {
                var user = await _appUserService.GetUser();
                ViewBag.Notifications = await _freindShipService.GetFreindRequestsReceive(user.Id);
                ViewBag.Name = user.FullName;
                ViewBag.UserImage = user.Image;
                return View(user);
            }
            return View();
        }
    }
}

Library/Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    @await Html.PartialAsync("~/Views/Partials/_Head.cshtml")
</head>

<body>
    @await Html.PartialAsync("~/Views/Partials/Toast.cshtml")
    @await Component.InvokeAsync("NavBar")
    <div class="page-wrapper">
        <div class="page-wrapper-inner">
            @await Html.PartialAsync("~/Views/Partials/_Sidebar.cshtml")
            <div class="page-content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
                @await Html.PartialAsync("~/Views/Partials/_Footer.cshtml")
            </div>
        </div>
    </div>
    @await Html.PartialAsync("~/Views/Partials/_Scripts.cshtml")
</body>

<script src="~/js/ej2.min.js"></script>
<ejs-scripts></ejs-scripts>
</html>